const DATA = {
  shipper_profile: {
    shipper_id: "SHP_20240318_001",
    company_name: "成都冷链通物流有限公司",
    contact_name: "王调度",
    contact_phone: "13812345678",
    account_type: "3PL",
    platform_join_date: "2023-06-15",
    account_manager: "李经理",
    monthly_cargo_count: 87,
    monthly_gtv: 2610000,
    avg_price_per_order: 30000,
    cancel_rate_30d: 0.08,
    fulfillment_rate_30d: 0.91,
    top_routes: [
      { route_id: "RT001", origin_city: "成都", origin_district: "青羊区", destination_city: "广州", destination_district: "白云区", monthly_count: 28, avg_price: 30000, avg_vehicle_length: "9.6米", main_goods_type: "冻品-猪肉" },
      { route_id: "RT002", origin_city: "成都", origin_district: "双流区", destination_city: "上海", destination_district: "浦东新区", monthly_count: 19, avg_price: 28000, avg_vehicle_length: "9.6米", main_goods_type: "冷鲜-水果" },
      { route_id: "RT003", origin_city: "成都", origin_district: "青羊区", destination_city: "北京", destination_district: "朝阳区", monthly_count: 15, avg_price: 38000, avg_vehicle_length: "13米", main_goods_type: "冻品-牛肉" },
      { route_id: "RT004", origin_city: "成都", origin_district: "锦江区", destination_city: "深圳", destination_district: "龙华区", monthly_count: 12, avg_price: 29000, avg_vehicle_length: "9.6米", main_goods_type: "冻品-海鲜" },
      { route_id: "RT005", origin_city: "成都", origin_district: "青羊区", destination_city: "重庆", destination_district: "渝北区", monthly_count: 13, avg_price: 8000, avg_vehicle_length: "9.6米", main_goods_type: "冷鲜-蔬菜" }
    ],
    cargo_habits: {
      payment_method: "到付",
      payment_method_ratio: { "到付": 0.82, "月结": 0.15, "预付": 0.03 },
      invoice_type: "普票",
      load_time_preference: "早上08:00",
      load_time_flexibility: "±1小时",
      goods_packaging: "托盘",
      special_requirements_template: "请司机提前30分钟到达，装货地有地磅",
      contact_at_origin: { name: "张仓管", phone: "13900001111" },
      contact_at_destination: { name: "李收货", phone: "13900002222" }
    },
    source_channels: [
      { channel_id: "CH001", channel_name: "客户甲微信群", channel_type: "wechat_group", input_type: "text_paste", format_template: "[出发地→目的地][货物][车长][时间][运费][付款]", parse_accuracy: 0.94, usage_count: 156 },
      { channel_id: "CH002", channel_name: "客户乙飞书表格", channel_type: "feishu_doc", input_type: "file_import", format_template: "Excel列顺序：发货地/收货地/货物名称/重量/车型/时间/运费", parse_accuracy: 0.97, usage_count: 89 },
      { channel_id: "CH003", channel_name: "客户丙单聊截图", channel_type: "wechat_single", input_type: "screenshot", format_template: "自然语言描述，格式不固定", parse_accuracy: 0.78, usage_count: 43 }
    ],
    preferred_drivers: {
      total_familiar_count: 23,
      diamond_count: 4,
      gold_count: 8,
      normal_count: 11,
      preferred_vehicle_length: ["9.6米", "13米"],
      preferred_vehicle_type: ["冷藏车"],
      blacklist_driver_ids: []
    }
  },
  driver_pool: [
    {
      driver_id: "DRV_001",
      name: "张建国",
      phone: "13700001001",
      familiar_level: "diamond",
      familiar_level_label: "🥇 钻石熟车",
      vehicle_type: "冷藏车",
      vehicle_length: "9.6米",
      vehicle_plate: "川A·88888",
      cold_machine: true,
      cold_machine_brand: "大冷",
      vehicle_width_wide: false,
      current_location: { province: "四川省", city: "成都市", district: "青羊区", address: "成都市青羊区光华大道附近", lat: 30.6598, lng: 104.0665, location_update_time: "2026-03-27 14:20", location_age_minutes: 76 },
      empty_status: "空车",
      empty_status_source: "司机主动上报",
      empty_status_update_time: "2026-03-27 13:45",
      idle_hours: 6,
      distance_to_origin_km: 18,
      cooperation_with_shipper: { total_orders: 12, last_order_date: "2026-03-24", last_order_route: "成都→广州", last_order_price: 30000, complaint_count: 0, cancel_count: 0, avg_rating: 4.9 },
      platform_stats: { total_orders_platform: 387, join_date: "2021-03-15", platform_rating: 4.9, cancel_rate: 0.03, on_time_rate: 0.97, main_routes: ["成都→广州", "成都→深圳", "成都→上海"], goods_experience: ["冻品", "冷鲜", "医药"] },
      wechat_enterprise: { in_enterprise_wechat: true, in_group: true, group_name: "成都冷链通-成都广州线", last_active_time: "2026-03-27 12:30" },
      price_negotiation_history: { accept_rate_plus80: 0.85, accept_rate_plus130: 0.60, accept_rate_plus180: 0.30, avg_accepted_delta: 95 }
    },
    {
      driver_id: "DRV_002",
      name: "陈大勇",
      phone: "13700001002",
      familiar_level: "diamond",
      familiar_level_label: "🥇 钻石熟车",
      vehicle_type: "冷藏车",
      vehicle_length: "9.6米",
      vehicle_plate: "川B·66666",
      cold_machine: true,
      cold_machine_brand: "凌达",
      vehicle_width_wide: false,
      current_location: { province: "四川省", city: "成都市", district: "双流区", address: "成都市双流区机场路附近", lat: 30.5788, lng: 103.947, location_update_time: "2026-03-27 13:00", location_age_minutes: 156 },
      empty_status: "空车",
      empty_status_source: "平台推算",
      idle_hours: 14,
      distance_to_origin_km: 31,
      cooperation_with_shipper: { total_orders: 8, last_order_date: "2026-03-18", last_order_route: "成都→广州", last_order_price: 29500, complaint_count: 0, cancel_count: 1, avg_rating: 4.8 },
      platform_stats: { total_orders_platform: 256, platform_rating: 4.8, cancel_rate: 0.05, on_time_rate: 0.94, main_routes: ["成都→广州", "成都→重庆"] },
      wechat_enterprise: { in_enterprise_wechat: true, in_group: true, group_name: "成都冷链通-成都广州线", last_active_time: "2026-03-26 18:00" },
      price_negotiation_history: { accept_rate_plus80: 0.75, accept_rate_plus130: 0.45, accept_rate_plus180: 0.20 }
    },
    {
      driver_id: "DRV_003",
      name: "李文强",
      phone: "13700001003",
      familiar_level: "gold",
      familiar_level_label: "🥈 黄金熟车",
      vehicle_type: "冷藏车",
      vehicle_length: "9.6米",
      vehicle_plate: "川A·55555",
      cold_machine: true,
      cold_machine_brand: "冷王",
      vehicle_width_wide: true,
      current_location: { province: "四川省", city: "成都市", district: "武侯区", address: "成都市武侯区天府大道附近", lat: 30.5728, lng: 104.065, location_update_time: "2026-03-27 10:00", location_age_minutes: 456 },
      empty_status: "未知",
      empty_status_source: "未知",
      idle_hours: null,
      distance_to_origin_km: 35,
      cooperation_with_shipper: { total_orders: 4, last_order_date: "2026-03-15", last_order_route: "成都→广州", last_order_price: 30500, complaint_count: 0, cancel_count: 0, avg_rating: 4.7 },
      platform_stats: { total_orders_platform: 134, platform_rating: 4.7, cancel_rate: 0.07, on_time_rate: 0.92, main_routes: ["成都→广州", "成都→深圳"] },
      wechat_enterprise: { in_enterprise_wechat: true, in_group: false, last_active_time: "2026-03-25 09:00" },
      price_negotiation_history: { accept_rate_plus80: 0.70, accept_rate_plus130: 0.40, accept_rate_plus180: 0.15 }
    },
    {
      driver_id: "DRV_004",
      name: "王海涛",
      phone: "13700001004",
      familiar_level: "normal",
      familiar_level_label: "🤝 普通熟车",
      vehicle_type: "冷藏车",
      vehicle_length: "13米",
      vehicle_plate: "川C·44444",
      cold_machine: true,
      vehicle_width_wide: false,
      current_location: { province: "四川省", city: "成都市", district: "新都区", address: "成都市新都区物流大道附近", lat: 30.823, lng: 104.158, location_update_time: "2026-03-27 15:10", location_age_minutes: 26 },
      empty_status: "空车",
      empty_status_source: "司机主动上报",
      idle_hours: 2,
      distance_to_origin_km: 42,
      cooperation_with_shipper: { total_orders: 2, last_order_date: "2026-02-20", last_order_route: "成都→北京", last_order_price: 38000, complaint_count: 0, cancel_count: 0, avg_rating: 4.6 },
      platform_stats: { total_orders_platform: 89, platform_rating: 4.6, cancel_rate: 0.09, on_time_rate: 0.90, main_routes: ["成都→北京", "成都→广州"] },
      wechat_enterprise: { in_enterprise_wechat: false, in_group: false }
    },
    {
      driver_id: "DRV_005",
      name: "赵志远",
      phone: "虚拟号_需发货后可见",
      familiar_level: "stranger",
      familiar_level_label: "🚗 附近优质司机",
      vehicle_type: "冷藏车",
      vehicle_length: "9.6米",
      vehicle_plate: "川A·33333",
      cold_machine: true,
      cold_machine_brand: "大冷",
      vehicle_width_wide: false,
      current_location: { province: "四川省", city: "成都市", district: "青羊区", address: "成都市青羊区光华大道（距装货地8km）", lat: 30.672, lng: 104.042, location_update_time: "2026-03-27 15:20", location_age_minutes: 16 },
      empty_status: "空车",
      empty_status_source: "司机主动上报",
      idle_hours: 1,
      distance_to_origin_km: 8,
      cooperation_with_shipper: { total_orders: 0, last_order_date: null, complaint_count: 0, cancel_count: 0 },
      platform_stats: { total_orders_platform: 203, platform_rating: 4.8, cancel_rate: 0.04, on_time_rate: 0.96, main_routes: ["成都→广州", "成都→深圳", "成都→上海"], route_experience_chengdu_guangzhou: 31 },
      wechat_enterprise: { in_enterprise_wechat: false, in_group: false, recruit_status: "可招募" },
      phone_visible: false,
      price_negotiation_history: { accept_rate_plus80: 0.65, accept_rate_plus130: 0.35, accept_rate_plus180: 0.10 }
    }
  ],
  market_data: {
    route_market_price: { route: "成都→广州", vehicle_type: "冷藏车", vehicle_length: "9.6米", goods_type: "冻品", date_range: "近14天", sample_count: 47, price_p25: 28500, price_p50: 30000, price_p75: 32000, price_min: 25000, price_max: 36000, trend: "下行", trend_delta_pct: -0.05, market_note: "当前市场供大于求，运价较去年同期下降约12%" },
    route_market_price_7d: { route: "成都→广州", vehicle_type: "冷藏车", vehicle_length: "9.6米", goods_type: "冻品", date_range: "近7天", sample_count: 22, price_p25: 29000, price_p50: 30200, price_p75: 32500, price_min: 26500, price_max: 35500, trend: "持平", trend_delta_pct: 0.0, market_note: "近7天价格相对稳定，供需基本均衡" },
    cost_estimation: { route: "成都→广州", vehicle_length: "9.6米", distance_km: 1680, fuel_cost: 6720, toll_cost: 1890, total_cost: 8610, net_income_at_30000: 21390, net_income_at_28500: 19890, net_income_at_32000: 23390 },
    destination_cargo_density: { city: "广州", vehicle_type: "冷藏车", vehicle_length: "9.6米", current_online_count: 23, daily_avg_7d: 19, peak_hour: "08:00-10:00", density_level: "充足", density_note: "广州是冷链货源密集城市，到达后通常1-2小时内可找到下一票" },
    transaction_speed: { route: "成都→广州", avg_time_to_first_feedback_min: 8, avg_time_to_deal_min: 23, deal_rate_in_1h: 0.78, best_publish_time: "07:00-09:00" }
  },
  risk_rules: [
    { rule_id: "RISK_001", level: "red", name: "卸货地址不精确", trigger_condition: "destination_address_detail 只填到市级或区级", cancel_rate_impact: "+26.7%", message: "⚠️ 卸货地址不够详细，司机容易因地址问题取消，建议补充到街道/门牌号", action: "block_until_fixed" },
    { rule_id: "RISK_002", level: "red", name: "装货时间模糊", trigger_condition: "load_time_start 包含模糊词", cancel_rate_impact: "+23.3%", message: "⚠️ 装货时间模糊是取消率第二大原因，请填写具体时间点", action: "block_until_fixed" },
    { rule_id: "RISK_003", level: "red", name: "冻品未填温度", trigger_condition: "冷链且温度为空", cancel_rate_impact: "+23.3%", message: "⚠️ 冷链货物未填温度要求，司机无法判断冷机是否匹配", action: "block_until_fixed" },
    { rule_id: "RISK_004", level: "yellow", name: "运费低于市场P25", trigger_condition: "freight_price < route_market_price.price_p25", message: "🟡 当前运费低于近14天市场价P25（¥28500），可能影响成交速度", action: "warn_only" },
    { rule_id: "RISK_005", level: "yellow", name: "重复发货检测", trigger_condition: "近24小时内存在相同出发地+目的地+品类的未完成货源", message: "🟡 检测到你有一票相同路线的货还在线，是否重复发货？", action: "confirm_required" },
    { rule_id: "RISK_006", level: "blue", name: "车型宽体未标注", trigger_condition: "重货且未标注宽体", message: "🔵 重货建议确认是否需要宽体车，避免装货时发现不匹配", action: "suggest_only" }
  ],
  demo: {
    sample_text: "[成都青羊→广州白云][冻品猪肉][9.6冷藏][明早8点][3万][到付]",
    sample_bulk_text: [
      "[成都青羊→广州白云][冻品猪肉][9.6冷藏][明早8点][3万][到付]",
      "[成都双流→上海浦东][冷鲜水果][9.6冷藏][明早9点][2.8万][到付]",
      "[成都青羊→重庆渝北][冷鲜蔬菜][9.6冷藏][今晚20点][8000][到付]"
    ].join("\n"),
    now: "2026-03-27 15:36",
    load_time: "2026-03-28 08:00",
    origin_address: "成都市青羊区光华大道三段188号冷链仓储中心B区",
    destination_address: "广州市白云区机场路1268号广州冷链物流园3号库",
    payment_method: "到付",
    invoice_type: "普票",
    special_requirements: "请司机提前30分钟到达，装货地有地磅",
    temp_requirement: "-18℃以下",
    freight_price: 30000
  }
};
window.DATA = DATA;
const FIELD_LABELS = {
  A01_origin_province: "出发省份",
  A02_origin_city: "出发城市",
  A03_origin_district: "出发区县",
  A04_origin_address_detail: "装货详细地址",
  A05_destination_province: "目的省份",
  A06_destination_city: "目的城市",
  A07_destination_district: "目的区县",
  A08_destination_address_detail: "卸货详细地址",
  B01_goods_category_l1: "货物一级品类",
  B02_goods_category_l2: "货物二级品类",
  B03_goods_weight_ton: "货物重量（吨）",
  B04_goods_volume_m3: "货物体积（方）",
  B05_goods_packaging: "包装方式",
  B06_temperature_requirement: "温度要求",
  B07_goods_count: "件数",
  C01_vehicle_type: "车型要求",
  C02_vehicle_length: "车长要求",
  C03_vehicle_width_wide: "是否需要宽体",
  C04_cold_machine_required: "是否需要独立冷机",
  D01_load_time_start: "最早装货时间",
  D02_load_time_end: "最晚装货时间",
  D03_expected_arrival_time: "要求到达时间",
  E01_freight_price: "运费（元）",
  E02_price_type: "定价方式",
  E03_payment_method: "付款方式",
  E04_invoice_type: "开票类型",
  F01_origin_contact_name: "装货联系人",
  F02_origin_contact_phone: "装货联系电话",
  F03_destination_contact_name: "卸货联系人",
  F04_destination_contact_phone: "卸货联系电话",
  G01_special_requirements: "特殊要求备注",
  G02_has_weigh_bridge: "是否有地磅",
  G03_loading_method: "装卸方式",
  G04_cargo_insurance: "是否需要货物保险"
};
window.FIELD_LABELS = FIELD_LABELS;
